### ISSUE TITLE
PHP Warning SG_iCal_Freq.php

### ISSUE THREAD

**Issue by dvarrel** [fangel/SG-iCalendar#17]
hello i've got 2 PHP Warning:
in_array() expects parameter 2 to be array, null given in SG_iCal_Freq.php on line 487
in_array() expects parameter 2 to be array, null given in SG_iCal_Freq.php on line 291

solution 
		if (is_array($this->excluded)) {
			.....
		}

best regards

**Comment by misterHippo** [comment]
Hi, 
I just came across this, and solved it with 
``if (!empty($this->excluded)&&in_array($t, $this->excluded)) { .... }``

Do you think there's any benefit to your solution (@dvarrel) over mine?

**Comment by dvarrel** [comment]
don't know :-)
